config/routes.rb
require 'sidekiq/web'

Crowdfund::Application.routes.draw do
  # match '/users/auth/:provider/callback', to: 'services#create'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations",
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
  }

  resources :users, :only => [:show] do
    get :get_complete_project, on: :collection
  end

  get "contacts/new"
  get "contacts/edit"
  get "image/new"
  get "set_new_perk" => "donations#set_new_perk"
  get "users/:user_id/profile" => "users#profile", as: "profile"

  match "browse/projects" => "pages#index", :as => "browse_projects"
  match "search/projects" => "pages#search", :as => "search_projects"

  get "projects/save_image"
  get "update_image" => "projects#update_image"
  get "galleries/save_image"
  get "galleries/delete_photo/:id" => "galleries#destroy", as: "delete_photo_via_get"
  get "galleries/delete_photo_tw_room/:id" => "galleries#delete_media_tw_room", as: "delete_media_tw_room"
  delete "galleries/delete_photo/:id" => "galleries#destroy", as: "delete_photo"
  delete "projects/:id/delete_image" => "projects#delete_image", as: "delete_image"
  get "projects/:project_id/sponsors/:id/confirmation" => "sponsors#confirmation", as: "confirmation"
  get "purchase" => "payments#purchase"
  get "projects/:project_id/sponsors/:sponsor_id/thank_you" => "sponsors#thank_you", as: "thank_you_for_sponsor"

  post "projects/save_image"
  post "galleries/save_image"
  post "galleries/save_photo_tw_room"
  post "share_email_by_sponsor" => "sponsors#share_email"
  post "share_email_by_donor" => "donations#share_email"

  post "projects/submit_project"
  post "update_sponsor_info" => "projects#update_sponsor_info"

  get "projects/stripe_update"
  get "default_perk_donations" => "donations#default_perk"

  post "#{Rails.root}/public/images/"

  get "admin/unapproved"
  post "admin/approve"

  get "/skip_sponsor" => "projects#skip_sponsor"

  resources :admin do
    get "deny", :on => :member
  end

  resources :s3_uploads
  namespace :project_admin do
    resources :documents do
      get "delete" => "documents#destroy", :on => :member
    end
    resources :projects do
      get "messages"
      get "overview"
      get "manage"
      get "detail"
      get "visual"
      get "cover_photo_and_gallery"
      get "post_to_social_media"
      get "emails_page"
      get "project_founder"
      get "project_update"
      get "photos_and_videos"
      get "communication_zone"

      collection do
        get "email_based_on_sponsor_level"
        post "send_email"
        post "process_project_update"
      end
    end
  end

  scope '/media' do
    resources :press_releases
    resources :press_coverages
  end

  resources :donations do
    get "thank_you", :on => :collection
    get "change_perk", :on => :member
    get "more_donators", :on => :member
    get "thank_you", :on => :collection
  end
  resources :projects do
    get :get_complete_project, on: :collection
    get :get_complete_project_public, on: :collection
    get "add_desc", :on => :collection
    get "set_previous_path_for_registration", :on => :collection
    get "set_previous_path_for_registration_perk", :on => :collection
    get "set_perk_to_false", :on => :collection
    get "update_content_assets_tab", :on => :collection
    get "update_sponsorship_content", :on => :collection
    get "update_td_mark", :on => :collection
    get "show_more_image", :on => :member
    post "add_perk", :on => :collection
    post "save_video", :on => :collection
    post "get_perk", :on => :collection
    post "update_perk", :on => :collection
    post "delete_perk", :on => :collection
    put "edit", :on => :collection
    get :download, on: :collection
    get :download_stripe_guide, on: :collection
    resources :sponsors do
      get :get_sponsorship_levels
      get :confirm_sponsor
    end
  end

  resources :projects

  resources :project_steps
  resources :donation_steps

  resources :services, :only => [:index, :create, :destroy]
  resources :newsletters, :only => [:create]
  #resources :services do
  #  get "index", :on => :collection
  #  get "create", :on => :collection
  #  get "destroy", :on => :collection
  #end

  resources :pages do
    get "search_category_or_location", :on => :collection
    get "discover", :on => :collection
    get "categories", :on => :collection
    post "contact", :on => :collection
    get "contact", :on => :collection
    post "contact_send", :on => :collection
    get "how_it_works", :on => :collection
    get "terms", :on => :collection
    get "about", :on => :collection
    get 'home', :on => :collection
    get "faqs", :on => :collection
    get "thank_you", :on => :collection
    get "privacy", :on => :collection
    get "funding_sources", :on => :collection
    get "media", :on => :collection
  end

  mount Sidekiq::Web => '/sidekiq'
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  root to: "pages#home"

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :default_perk
	before_filter :authenticate_user!
  before_filter :set_session_page, :set_session_wizard, :set_previous_path_for_registration
  layout "landing"

  def new
    @donation = Donation.new
    @perk = Perk.find(params[:perk])
    @perk_name = params[:name].to_s
    @perk_amount = params[:amount].gsub(",", "").to_f
    @perk_description = params[:description]
    @project = Project.find(params[:project_id])
    @perks = @project.perks.order(:amount).map{ |perk| [perk.name, perk.amount.to_i] }
    session[:perk_id] = params[:perk]
  end

  def default_perk
    @donation = Donation.new
    @perk = Perk.new
    @perk_name = params[:name].to_s
    @perk_amount = params[:amount].gsub(",", "").to_f
    @perk_description = params[:description]
    @project = Project.find(params[:project_id])
    if params[:amount].blank?
      @perks = @project.perks.order(:amount).map{ |perk| [perk.name, perk.amount.to_i] }
      session[:perk_id] = "custom_donate"
    else
      if @project.perk_permission
        perks = @project.perks.order(:amount).map{ |perk| [perk.name, perk.amount.to_i, perk.id, perk.description, perk.perks_available] }
      else
        perks = DEFAULT_PERK
      end
      @perks = []
      perks.each do |perk|
        if perk[1].to_f <= params[:amount].gsub(",", "").to_f
          if !perk[4].blank? && perk[4].to_i > 0
            @perks.push(perk)
          elsif perk[4].blank?
            @perks.push(perk)
          end
        end
      end

      if !@project.perk_permission
        amount = params[:amount].to_f
        @perk_description = "#{params[:amount].to_i} Uruut Reward Points"
        if amount < 10
          @perk_name_selected = "Custom"
        elsif amount < 25
          @perk_name_selected = "Level 1"
        elsif amount < 50
          @perk_name_selected = "Level 2"
        elsif amount < 100
          @perk_name_selected = "Level 3"
        elsif amount < 250
          @perk_name_selected = "Level 4"
        else
          @perk_name_selected = "Level 5"
        end
      elsif @perks.blank?
        @perk_name_selected = "No Perk"
        @perk_description = ""
      else
        @perk_name_selected = @perks.last[0]
        @perk_description = @perks.last[3]
      end

      if @perks.blank?
        session[:perk_id] = "Custom"
      elsif @project.perk_permission
        session[:perk_id] = @perks.last[2]
      else
        session[:perk_id] = @perks.last[0]
      end
    end
    render :new
  end

  def change_perk
    if !params[:id].eql?("custom")
      if params["amount"].blank?
        @perk = Perk.find(params[:id])
        @project = Project.find(params["project_id"])
        session[:perk_id] = @perk.id
        session[:perk_amount] = @perk.amount.to_f
        @perk_description = @perk.description
      else
        @perk = Perk.new
        @perk.id = params["level"]
        @perk.amount = params["amount"].gsub(",", "").to_f
        session[:perk_amount] = @perk.amount.to_f
        @project = Project.find(params["project_id"])
        if @project.perk_permission
          perks = @project.perks.order(:amount).map{ |perk| [perk.name, perk.amount.to_i, perk.id, perk.description, perk.perks_available] }
        else
          perks = DEFAULT_PERK
        end
        @perks = []
        perks.each do |perk|
          if perk[1].to_f <= params[:amount].gsub(",", "").to_f
            if !perk[4].blank? && perk[4].to_i > 0
              @perks.push(perk)
            elsif perk[4].blank?
              @perks.push(perk)
            end
          end
        end
        @perk_name_selected = @perks.last[0]
        @perk_description = @perks.last[3]
        if @project.perk_permission
          session[:perk_id] = @perks.last[2]
        else
          session[:perk_id] = @perks.last[0]
        end
        @perk.name = "Level #{@perk.id}"
        @perk.description = "You will receive #{@perk.amount.to_i} Uruut Reward Points when you seed $#{@perk.amount.to_i}"
      end
    else
      @perk = Perk.new
      @perk.id = params["level"]
      @perk.amount = params["custom_seed"].gsub(",", "")
      @project = Project.find(params["project_id"])
      if @project.perk_permission
        perks = @project.perks.order(:amount).map{ |perk| [perk.name, perk.amount.to_i, perk.id, perk.description, perk.perks_available] }
      else
        perks = DEFAULT_PERK
      end
      @perks = []
      perks.each do |perk|
        if perk[1].to_f <= params["custom_seed"].gsub(",", "").to_f
          if !perk[4].blank? && perk[4].to_i > 0
            @perks.push(perk)
          elsif perk[4].blank?
            @perks.push(perk)
          end
        end
      end

      if !@project.perk_permission
        amount = params[:custom_seed].to_f
        @perk_description = "#{params[:custom_seed].to_i} Uruut Reward Points"
        if amount < 10
          @perk_name_selected = "Custom"
        elsif amount < 25
          @perk_name_selected = "Level 1"
        elsif amount < 50
          @perk_name_selected = "Level 2"
        elsif amount < 100
          @perk_name_selected = "Level 3"
        elsif amount < 250
          @perk_name_selected = "Level 4"
        else
          @perk_name_selected = "Level 5"
        end
      elsif @perks.blank?
        @perk_name_selected = "No Perk"
        @perk_description = ""
      else
        @perk_name_selected = @perks.last[0]
        @perk_description = @perks.last[3]
      end

      if @perks.blank?
        session[:perk_id] = "Custom"
      elsif @project.perk_permission
        session[:perk_id] = @perks.last[2]
      else
        session[:perk_id] = @perks.last[0]
      end
      session[:perk_amount] = @perk.amount.to_f
      @perk.name = "Custom"
      @perk.description = "You will receive #{@perk.amount} Uruut Reward Points when you seed $#{@perk.amount}"
    end
  end

  def create
    if params[:perk_type].eql?("default")
      params[:donation][:description] = "#{params[:donation][:amount].to_i} Uruut Reward Points"
    else
      params[:donation][:description] = params[:perk_description]
    end
    params[:donation][:perk_name] = params[:name_of_perk]
    @donation = Donation.new(params[:donation])
    @donation.confirmed = false

    if @donation.save
      session.merge!(:donation_id => @donation.id, :card_token => @donation.token, :card_type => @donation.card_type,
                     :card_last4 => @donation.card_last4)
      session[:perk_type] = params[:perk_type]
      session[:payment_amount] = params[:donation][:amount]
      session[:project_id_of_perk_selected] = params[:donation][:project_id]
      session[:perk_amount] = params[:donation][:amount]
      redirect_to donation_steps_path
    else
      render :new
    end

    # @donation = Donation.new(params[:donation])
    # @token = @donation.token
    # if @donation.save_with_payment
    #  redirect_to project_url(@donation.project_id), :notice => "Thank you for contributing!"
    # else
    #  render :new
    # end

    # ### new function for payment ###
    # @error_payment = @donation.error_payment?
    # if @error_payment
    #   # render :new
    #   redirect_to :back, notice: @error_payment
    # else
    #   redirect_to donation_steps_path
      # redirect_to project_url(@donation.project_id), :notice => "Thank you for contributing!"
    # end

  end

  def edit
    @donation = Donation.unscoped.find(params[:id])
    @project = @donation.project
    perks = @project.perks.order(:amount).map{ |perk| [perk.name, perk.amount.to_i, perk.id] }
    @perks = []
    perks.each do |perk|
      if perk[1].to_f <= @donation.amount.to_f
        @perks.push(perk)
      end
    end
    @perk_name_selected = @donation.perk_name
    @donation.save!
  end

  def set_new_perk
    perk = Perk.where(name: params[:perk_name], project_id: params[:project_id]).first
    @perk_name_selected = perk.name
    @perk_description = perk.description
    if perk.nil?
      session[:perk_id] = params[:name_of_perk]
    else
      session[:perk_id] = perk.id
    end
    respond_to :js
  end

  def update
    # donation = Donation.new(params[:donation])
    # donation.token = params[:donation][:token]

    # @error_payment = donation.error_payment?
    # if @error_payment
    #   redirect_to :back, notice: @error_payment
    # else
    @donation = Donation.unscoped.find(params[:id])
    session[:card_last4] = params[:donation][:card_last4]
    session[:card_type] = params[:donation][:card_type]
    params[:donation][:perk_name] = params[:name_of_perk]
    params[:donation][:amount] = session[:perk_amount]
    params[:donation][:description] = params[:perk_description]
    # unit = params[:donation][:amount].last
    # case unit
    #   when "K"
    #     params[:donation][:amount] = params[:donation][:amount].to_i * 1000
    #   when "M"
    #     params[:donation][:amount] = params[:donation][:amount].to_i * 1000000
    #   when "B"
    #     params[:donation][:amount] = params[:donation][:amount].to_i * 1000000000
    #   when "T"
    #     params[:donation][:amount] = params[:donation][:amount].to_i * 1000000000000
    #   when "Q"
    #     params[:donation][:amount] = params[:donation][:amount].to_i * 1000000000000000
    # end
    session[:payment_amount] = params[:donation][:amount]
    current_user.update_attributes(uruut_point: session[:payment_amount])
    if params[:donation][:amount].is_a?(String)
      params[:donation][:amount] = params[:donation][:amount].gsub('$', '').gsub(',', '').to_f
    end
    if @donation.update_attributes(params[:donation])
     flash[:notice] = "Successfully updated donation."
   end
   redirect_to donation_steps_path
    # end
  end

  def more_donators
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html { redirect_to project_url(@project), notice: "successfully" }
      format.js
    end
  end

  def thank_you

app/helpers/donations_helper.rb
module DonationsHelper

	def current_user_id
		current_user.id
	end
end

app/views/donations/_edit.html.haml
= form_for(@donation, :url => donation_path) do |f|
  - if @donation.errors.any?
    .error_messages
      %h2
        = pluralize(@donation.errors.count, "error")
        prohibited this subscription from being saved:
      %ul
        - @donation.errors.full_messages.each do |msg|
          %li= msg
  / = f.hidden_field :plan_id
  = f.hidden_field :token
  = f.hidden_field :card_type
  = f.hidden_field :card_last4
  = f.hidden_field :email, :value => "#{current_user.email}"
  = f.hidden_field :user_id, :value => "#{current_user.id}"
  = f.hidden_field :project_id, :value => "#{current_project}"
  - if @donation.token.present?
    Credit card has been provided.
  - else
    .field
      / = label_tag :amount, "Amount to Donate"
      = hidden_field_tag :amount, session[:perk_amount], name: "donation[amount]"
      = hidden_field_tag :perk_permission_type, @project.perk_permission ? "custom" : "default" , name: "perk_type"
      = hidden_field_tag :name_of_perk, @donation.perk_name
      = hidden_field_tag :perk_description, @donation.description, class: "dua"
    .req-legend
      *Required
    .field.name
      = label_tag nil, class: "label-green" do
        NAME AS IT APPEARS ON CARD*
        %span.error-container
      = text_field_tag nil, [current_user.first_name, current_user.last_name].join(" "), name: "name", id: "name"
    .field.card-number
      = label_tag :card_number, class: "label-green" do
        Credit Card Number*
        %span.error-container
      = text_field_tag :card_number, nil, name: "credit-card"
    .field.ccv
      = label_tag :card_code, "CVV*", class: "label-green"
      = text_field_tag :card_code, nil, name: "code", maxlength: 4, style: "display: inline-block;"
      %span.error-container.beside-form
    .field.expiration
      = label_tag :card_month, "CARD EXPIRATION (MM/YYYY)*", class: "label-green"
      / = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}
      / = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}
      = text_field_tag nil, nil, {name: "month", id: "card_month"}
      = text_field_tag nil, nil, {name: "year", id: "card_year"}
      %span.error-container.beside-form
    .cf
  #stripe_error
    - if notice
      = notice
    %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.

  .actions
    %hr
    %p{:style => "font:normal 12px/18px 'Proxima Nova';color:#403e37"}
      %span{:style => "Proxima Nova Bold"}
        Note:
      Your card will not be charged when you make your investment! You will only be charged if this campaign reaches its funding goal. All transactions are processed through a secure third-party payment processor.
    = button_tag :type => 'submit', :id => "donate", :class => "btn" do
      Contribute ►
    .cf

= javascript_include_tag "donations"

app/views/donations/_form.html.haml
= form_for @donation do |f|
  - if @donation.errors.any?
    .error_messages
      %h2
        = pluralize(@donation.errors.count, "error")
        prohibited this subscription from being saved:
      %ul
        - @donation.errors.full_messages.each do |msg|
          %li= msg
  / = f.hidden_field :plan_id
  = f.hidden_field :token
  = f.hidden_field :card_type
  = f.hidden_field :card_last4
  = f.hidden_field :email, :value => "#{current_user.email}"
  = f.hidden_field :user_id, :value => "#{current_user.id}"
  = f.hidden_field :project_id, :value => "#{current_project}"
  - if @donation.token.present?
    Credit card has been provided.
  - else
    .field
      / = label_tag :amount, "Amount to Donate"
      - perk_name = @perk_name_selected.blank? ? @perk_name : @perk_name_selected
      = hidden_field_tag :amount, @perk_amount, name: "donation[amount]"
      = hidden_field_tag :perk_permission_type, @project.perk_permission ? "custom" : "default" , name: "perk_type"
      = hidden_field_tag :name_of_perk, perk_name, class: "dua"
      = hidden_field_tag :perk_description, @perk_description, class: "dua"
    .req-legend
      *Required
    .field.name
      = label_tag nil, class: "label-green" do
        NAME AS IT APPEARS ON CARD*
        %span.error-container
      = text_field_tag nil, [current_user.first_name, current_user.last_name].join(" "), name: "name", id: "name"
    .field.card-number
      = label_tag :card_number, class: "label-green" do
        Credit Card Number*
        %span.error-container
      = text_field_tag :card_number, nil, name: "credit-card"
    .field.ccv
      = label_tag :card_code, "CVV*", class: "label-green"
      = text_field_tag :card_code, nil, name: "code", maxlength: 4, style: "display: inline-block;"
      %span.error-container.beside-form{style: "float: none; margin-left: 12px;"}
    .field.expiration
      = label_tag :card_month, "CARD EXPIRATION (MM/YYYY)*", class: "label-green"
      / = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}
      / = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}
      = text_field_tag nil, nil, {name: "month", id: "card_month", maxlength: 2}
      = text_field_tag nil, nil, {name: "year", id: "card_year", maxlength: 4}
      %span.error-container.beside-form
    .cf
  #stripe_error
    - if notice
      = notice
    %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
  %div.anonymous-check
    = f.label :anonymous, class: "label-green" do
      ANONYMOUS DONATION
      %span.error-container
    = f.check_box :anonymous, {label: false, style: "margin-bottom: 5px"}
    I would like to make this donation anonymously.
    .content-anonymous{style: "display: none"}
      (If checked, your information will be witheld from the project owner as well as from any other audience, and you will not receive the selected perk.)
  .actions
    %hr
    %p{:style => "font:normal 12px/18px 'Proxima Nova';color:#403e37"}
      %span{:style => "Proxima Nova Bold"}
        Note:
      Your card will not be charged when you make your investment! You will only be charged if this campaign reaches its funding goal. All transactions are processed through a secure third-party payment processor.
    = button_tag :type => 'submit', :id => "donate", :class => "btn" do
      Contribute ►
    .cf

= javascript_include_tag "donations"

app/views/donations/_more_donators.html.haml
- @project.distinct_donors.each do |donator|
  - if user_signed_in?
    - if donator.anonymous
      = link_to(image_tag("anonymous.png", style: "width: 27px; height:27px; margin-bottom: 5px; border-radius: 500px 500px 500px 500px; behavior: url('assets/PIE-1.0.0/PIE.htc');", "data-toggle" => "tooltip", title: "ANONYMOUS DONOR", class: "donor-anonymous"), "javascript:void(0)")
    - else
      = link_to(image_tag(donator.user.avatar, style: "width: 27px; height:27px; margin-bottom: 5px; border-radius: 500px 500px 500px 500px;"), profile_path(donator.user.id))
  - else
    - if donator.anonymous
      = link_to(image_tag("anonymous.png", style: "width: 27px; height:27px; margin-bottom: 5px; border-radius: 500px 500px 500px 500px; behavior: url('assets/PIE-1.0.0/PIE.htc');", "data-toggle" => "tooltip", title: "ANONYMOUS DONOR", class: "donor-anonymous"), "javascript:void(0)")
    - else
      = link_to(image_tag(donator.user.avatar, style: "width: 27px; height:27px; margin-bottom: 5px; border-radius: 500px 500px 500px 500px;"), "javascript:void(0)", "url-data" => "/users/#{donator.user.id}/profile", class: "unsignin")

app/views/donations/more_donators.js.erb
<% if params[:logged_in].eql?("yes") %>
$(".business").html("<%=j render 'more_donators' %>");
$(".more").fadeOut("slow");
<% else %>
window.location.href = "<%= session[:redirect_url] %>";
<% end %>

app/views/donations/set_new_perk.js.erb
$("#name_of_perk").val("<%= @perk_name_selected %>");
$("#perk_description").val("<%= @perk_description %>");
$(".perk-description").text("<%= @perk_description %> ")
$(".perk-name").text("<%= @perk_name_selected %>")

app/views/donations/thank_you.html.haml
.container
  .row-fluid{style: "margin-top: 30px;"}
    .span9
      %h4.tittle{style: "padding-bottom: 10px;"} THANK YOU!
      %h4.label-green Congratulations!
      %p{:style => "letter-spacing: 1px;"} You are now an official donor to #{session[:donation_thank_you][:project_title]}. Now it's time to spread the word
      %div
        = link_to image_tag("fb-share.png",style: "width: 150px"), "https://www.facebook.com/dialog/feed?app_id=#{Settings.facebook.api_key}&link=#{project_url(session[:donation_thank_you][:project_id])}&picture=#{session[:donation_thank_you][:project_large_image]}&name=#{url_encode(session[:donation_thank_you][:project_url])}&caption=#{url_encode(session[:donation_thank_you][:project_title])}&description=#{url_encode("I'm RUUTing for this community project and you should, too. Join me by making a donation on @URUUT’s collaborative funding platform. Let's make a difference in our community!")}&redirect_uri=#{thank_you_donations_url}", style: "display: block; float: left;", target: "_blank"
        = image_tag "tw-share.png", style: "cursor:pinter; margin-left: 2%; display: block; float: left; width: 150px; cursor:pointer", class: "tw-share"
        = link_to image_tag("ml-share.png", style: "width: 150px"), "javascript:void(0)", style: "margin-left: 2%; display: block; float: left;", class: "cs_import"
        %span.link-short{:style => "font-weight:bolder; font-size: 18px !important; margin-left: 2%"}
          = session[:donation_thank_you][:project_bitly]

    .span3.pull-right.messages-content
      %h4.title Details
      .well.pull-left{style: "margin-left: 0;"}
        %h5.label-green{style: "margin-bottom: 0;"} Payment amount
        %p #{number_to_currency(session[:donation_thank_you][:amount], :precision => 0)}
        %h5.label-green{style: "margin-bottom: 0;"} Your perk
        %h6{style: "margin: 0;"}
          = session[:donation_thank_you][:perk_name]
        %p= session[:donation_thank_you][:perk_description]
        %p{style: "color: #e0e0e0; font-size: 11px;"}
          %span{style: "font-family: 'Proxima Nova Semi', sans-serif;"}
            Estimated delivery :
          13 October 2013

:javascript
  var project_id = "#{session[:donation_thank_you][:project_id]}";

  $('.tw-share').click(function(e) {
    e.preventDefault();
    var url = "http://twitter.com/share?url=#{session[:donation_thank_you][:bitly]}&text=I%27m%20RUUTing%20for%20this%20community%20project%20on%20%40URUUT%20and%20you%20should%2C%20too.%20Join%20me%20in%20making%20a%20donation%3A%20%2E&hashtags=GetRUUTed";

    window.open(url);
  });

  var owner_email, owner_first_name, owner_last_name;
  var appendInTextarea = false;
  var emailSep = ", ";
  function sendEmail(contacts, source, owner) {
    var contact, name, email, entry;
    var emails = [];
    var textarea = document.getElementById('contact_list');

    for (var i = 0; i < contacts.length; i++) {
      contact = contacts[i];
      name = contact.fullName();
      email = contact.selectedEmail();
      entry = name + "<" + email +">";
      if (emails.indexOf(entry) < 0) {
        emails.push(entry);
      }
    }

    $("#contact_list").val("");

    $.ajax({
      type: "POST",
      url: "/share_email_by_donor",
      data: {emails: emails.join(emailSep), project_id: project_id, user_id: #{current_user.id}}
    })

  }


  var csPageOptions = {
    domain_key:"#{Settings.cloudsponge.api_key}", // default for 127.0.0.1, please change it
    textarea_id:"contact_list",
    afterSubmitContacts:sendEmail
  };

%script{:src => "https://api.cloudsponge.com/address_books.js"}