config/routes.rb
require 'sidekiq/web'

Crowdfund::Application.routes.draw do
  # match '/users/auth/:provider/callback', to: 'services#create'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations",
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
  }

  resources :users, :only => [:show] do
    get :get_complete_project, on: :collection
  end

  get "contacts/new"
  get "contacts/edit"
  get "image/new"
  get "set_new_perk" => "donations#set_new_perk"
  get "users/:user_id/profile" => "users#profile", as: "profile"

  match "browse/projects" => "pages#index", :as => "browse_projects"
  match "search/projects" => "pages#search", :as => "search_projects"

  get "projects/save_image"
  get "update_image" => "projects#update_image"
  get "galleries/save_image"
  get "galleries/delete_photo/:id" => "galleries#destroy", as: "delete_photo_via_get"
  get "galleries/delete_photo_tw_room/:id" => "galleries#delete_media_tw_room", as: "delete_media_tw_room"
  delete "galleries/delete_photo/:id" => "galleries#destroy", as: "delete_photo"
  delete "projects/:id/delete_image" => "projects#delete_image", as: "delete_image"
  get "projects/:project_id/sponsors/:id/confirmation" => "sponsors#confirmation", as: "confirmation"
  get "purchase" => "payments#purchase"
  get "projects/:project_id/sponsors/:sponsor_id/thank_you" => "sponsors#thank_you", as: "thank_you_for_sponsor"

  post "projects/save_image"
  post "galleries/save_image"
  post "galleries/save_photo_tw_room"
  post "share_email_by_sponsor" => "sponsors#share_email"
  post "share_email_by_donor" => "donations#share_email"

  post "projects/submit_project"
  post "update_sponsor_info" => "projects#update_sponsor_info"

  get "projects/stripe_update"
  get "default_perk_donations" => "donations#default_perk"

  post "#{Rails.root}/public/images/"

  get "admin/unapproved"
  post "admin/approve"

  get "/skip_sponsor" => "projects#skip_sponsor"

  resources :admin do
    get "deny", :on => :member
  end

  resources :s3_uploads
  namespace :project_admin do
    resources :documents do
      get "delete" => "documents#destroy", :on => :member
    end
    resources :projects do
      get "messages"
      get "overview"
      get "manage"
      get "detail"
      get "visual"
      get "cover_photo_and_gallery"
      get "post_to_social_media"
      get "emails_page"
      get "project_founder"
      get "project_update"
      get "photos_and_videos"
      get "communication_zone"

      collection do
        get "email_based_on_sponsor_level"
        post "send_email"
        post "process_project_update"
      end
    end
  end

  scope '/media' do
    resources :press_releases
    resources :press_coverages
  end

  resources :donations do
    get "thank_you", :on => :collection
    get "change_perk", :on => :member
    get "more_donators", :on => :member
    get "thank_you", :on => :collection
  end
  resources :projects do
    get :get_complete_project, on: :collection
    get :get_complete_project_public, on: :collection
    get "add_desc", :on => :collection
    get "set_previous_path_for_registration", :on => :collection
    get "set_previous_path_for_registration_perk", :on => :collection
    get "set_perk_to_false", :on => :collection
    get "update_content_assets_tab", :on => :collection
    get "update_sponsorship_content", :on => :collection
    get "update_td_mark", :on => :collection
    get "show_more_image", :on => :member
    post "add_perk", :on => :collection
    post "save_video", :on => :collection
    post "get_perk", :on => :collection
    post "update_perk", :on => :collection
    post "delete_perk", :on => :collection
    put "edit", :on => :collection
    get :download, on: :collection
    get :download_stripe_guide, on: :collection
    resources :sponsors do
      get :get_sponsorship_levels
      get :confirm_sponsor
    end
  end

  resources :projects

  resources :project_steps
  resources :donation_steps

  resources :services, :only => [:index, :create, :destroy]
  resources :newsletters, :only => [:create]
  #resources :services do
  #  get "index", :on => :collection
  #  get "create", :on => :collection
  #  get "destroy", :on => :collection
  #end

  resources :pages do
    get "search_category_or_location", :on => :collection
    get "discover", :on => :collection
    get "categories", :on => :collection
    post "contact", :on => :collection
    get "contact", :on => :collection
    post "contact_send", :on => :collection
    get "how_it_works", :on => :collection
    get "terms", :on => :collection
    get "about", :on => :collection
    get 'home', :on => :collection
    get "faqs", :on => :collection
    get "thank_you", :on => :collection
    get "privacy", :on => :collection
    get "funding_sources", :on => :collection
    get "media", :on => :collection
  end

  mount Sidekiq::Web => '/sidekiq'
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  root to: "pages#home"

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :filename, :url, :project_id
  belongs_to :project
end

app/controllers/project_admin/documents_controller.rb
class ProjectAdmin::DocumentsController < ApplicationController
  before_filter :set_project, except: :destroy

  def index
    @authenticated = admin_required!
    @documents = @project.documents.page(params[:page]).per(9) if @authenticated
  end

  def create
    @document = Document.create(filename: params[:filename], url: params[:url],  project_id: @project.id)
  end

  def destroy
    Document.delete(params[:id])
    render :text => "Success"
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def admin_required!
   unless current_user.is_admin?
    @project.user.id.eql?(current_user.id) ? true : false
   end
 end

end

app/controllers/project_admin/projects_controller.rb
class ProjectAdmin::ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_project, only: :show
  before_filter :set_project_ajax, except: [:index, :update, :show,
    :send_email, :email_based_on_sponsor_level, :project_update, :process_project_update]

  respond_to :js, except: [:index, :update, :show, :emails_page, :messages]
  has_scope :page, :default => 1
  layout false, :only => "stripe_update"

  def index
    @projects = Project.find(params[:id])
  end

  def show
    subheader
    @fundings = @project.all_funding_by_project(params[:page])
    @total_fundings = @project.total_funding_by_project

    respond_to do |format|
      format.js
      format.html
    end
  end

  def messages
    subheader
    @fundings = @project.all_funding_by_project(params[:page])
    @total_fundings = @project.total_funding_by_project

    respond_to do |format|
      format.js
      format.html
    end
  end

  def overview; end

  def manage
    @galleries = @project.galleries.page(params[:page]).per(6)
  end

  def detail; end

  def visual; end

  def project_update
    @project_update = ProjectUpdate.new
    session[:current_project] = params[:project_id]
  end

  def process_project_update
    params[:project_update][:project_id] = session[:current_project]
    project_update = ProjectUpdate.new(params[:project_update])
    project_update.save
    @alert = "Project successfully updated"
  end

  def cover_photo_and_gallery
    @galleries = @project.galleries.page(params[:page]).per(6)
  end

  def post_to_social_media; end

  def project_founder
    @project = Project.find(params[:project_id])

    if params[:type].blank?
      @founders = @project.founders(params[:page])
      @all = true
    else
      @founders = if params[:type].eql?("individual")
        @project.individual_donors(params[:page])
      else
        @project.project_sponsor_by_level(params[:page])
      end
      @all = false
    end
  end

  def send_email
    @error_messages = []

    @error_messages << "email recipient can't be blank" if params[:email_recepient].blank?
    @error_messages << "email subject can't be blank" if params[:post]["subject"].blank?
    @error_messages << "email content can't be blank" if params[:post]["email_content"].blank?

    if @error_messages.blank?
      subject = params[:post][:subject]
      recepients = params[:email_recepient].split(",")
      recepients.each do |recepient|
        ProjectMailer.project_message(recepient, params[:post]["subject"], params[:email_header], params[:post]["email_content"]).deliver
      end
    end
  end

  def emails_page
    @project = Project.find(params[:project_id])
    @total_fundings = @project.total_funding_by_project
    @contact = Contact.new
    @need_doctype = true
    @list_recepients = @project.list_recepient

    subheader
  end

  def email_based_on_sponsor_level
    project = Project.find(session[:current_project])
    case params[:level_id]
    when "All Project Sponsors and Donors"
      emails_sponsor = project.project_sponsors.joins(:sponsor).pluck(:email).uniq
      emails_donors = project.donations.where(anonymous: false).pluck(:email).uniq
      emails = emails_donors + emails_sponsor
    when "All Project Sponsors"
      emails = project.project_sponsors.joins(:sponsor).pluck(:email).uniq
    when "All Project Donors"
      emails = project.donations.where(anonymous: false).pluck(:email).uniq
    when "My Contacts"
      emails = []
    else
      if params[:level_id].to_i.to_s == params[:level_id]
        emails = project.project_sponsors.joins(:sponsor).where("level_id = ?", params[:level_id]).uniq.pluck(:email)
      else
        level_name = params[:level_id].split(" Project")
        emails = project.donations.where(anonymous: false).where("perk_name = ?", level_name[0]).uniq.pluck(:email)
      end
    end

    emails.reject!(&:empty?)
    @emails = emails.join(",")
  end

  def photos_and_videos
    @photos_and_videos = @project.galleries.media_transparent_room(params[:page])
  end

  def communication_zone
    @test = "test"
    respond_to do |format|
      format.js
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
    admin_required!
  end

  def set_project_ajax
    @project = Project.find(params[:project_id])
    session[:current_project] = @project.id
    admin_required!
  end

  def subheader
    @donations = Donation.find_all_by_project_id(@project.id)
    @sponsors = ProjectSponsor.where(project_id: @project.id)
    @sponsor_count = @sponsors.empty? ? 0 : @sponsors.count
  end

  def admin_required!
     unless current_user.is_admin?
      unless @project.user.id.eql?(current_user.id)
       flash[:error] = "Sorry, you don't have right permision to accessing page."
       redirect_to root_url and return false
      end
     end
  end

end

app/views/project_admin/documents/_document_room.html.haml
%div
  %h2.title.document-room DOCUMENT ROOM
  .project-funder.well{:style => "padding-left: 5%"}
    .row
      .span6.pull-left
        = label_tag "document", "UPLOAD A NEW DOCUMENT", class: "label-green"
        = link_to "UPLOAD A DOCUMENT ►", "javascript:void(0)", :class => "btn new-document-button", :id => "project-submit", :style => "border-radius: 5px;", project_id: @project.id
      .span6.pull-left
        %span Note:
        You should upload any and all applicable documents including, schedules, receipts, plans, blueprints, etc. Acceptable file types include .doc, .pdf, .ppt, .txt and .xls
    %hr
    = label_tag "current_document", "CURRENT DOCUMENTS", class: "label-green"
    .images-content{:style => "width:100%"}
      #galleryPicture.clearfix
        - @documents.each do |document|
          .list-image.pull-left
            = image_tag(document_thumbnail(document.url, 216), style: "height: 222px; width: 222px")
            = link_to "delete", "javascript:void(0)", class: "image-delete-button", "data-href" => delete_project_admin_document_path(document.id), rel: "tooltip", title: "delete this document"
      = paginate @documents, remote: true

= javascript_include_tag "transparency_workroom"

app/views/project_admin/documents/_index.html.haml
.container.messages-page
  .row-fluid
    .span3.pull-left
      %div{:style => "margin-top: 60px"}
      %div{:class => "well info"}
        %h3{:class => "menu-messages document active"}
          = link_to "DOCUMENT ROOM", "/project_admin/documents?project_id=#{@project.id}", remote: true
          .arrow
        %h3{:class => "menu-messages photos-videos"}
          = link_to "PHOTOS & VIDEOS", project_admin_project_photos_and_videos_path(@project.id), remote: true
        %h3{:class => "menu-messages communication"}
          = link_to "COMMUNICATION", project_admin_project_communication_zone_path(@project.id), remote: true
    .span9.pull-right.content-workroom
      = render "document_room"

app/views/project_admin/documents/_new_document.html.haml
.list-image.pull-left
  = image_tag(document_thumbnail(@document.url, 216), style: "height: 222px; width: 222px")
  = link_to "delete", "javascript:void(0)", class: "image-delete-button", "data-href" => delete_project_admin_document_path(@document.id), rel: "tooltip", title: "delete this document"

app/views/project_admin/documents/create.js.erb
$("#galleryPicture").append("<%=j render 'new_document' %>");

app/views/project_admin/documents/edit.html.erb
<h1>Editing project_admin_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_admin_document %> |
<%= link_to 'Back', project_admin_documents_path %>

app/views/project_admin/documents/index.js.erb
<% if @authenticated %>
$(".admin-menu li").removeClass("active");
$(".workroom").parent().addClass("active");

$('.sub-menu-project').removeClass('active');
$('.workroom').addClass('active').append("<div class='arrow'></div>").append('<div class="arrow"></div>');
$('.main-content').html("<%=j render 'index' %>");
<% else %>
window.location.href = "<%= root_url %>";
<% end %>